config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  # Hoptoad Notifier Routes
  match '/notifier_api/v2/notices' => 'notices#create', via: [:get, :post]
  get '/locate/:id' => 'notices#locate', :as => :locate

  resources :notices, only: [:show]
  resources :users do
    member do
      delete :unlink_github
      delete :unlink_google
    end
  end

  resources :site_config, only: [:index] do
    collection do
      put :update
    end
  end

  resources :problems, only: [:index] do
    collection do
      post :destroy_several
      post :resolve_several
      post :unresolve_several
      post :merge_several
      post :unmerge_several
      get :search
    end
  end

  resources :apps do
    resources :problems do
      resources :notices
      resources :comments, only: [:create, :destroy]

      collection do
        post :destroy_all
      end

      member do
        put :resolve
        put :unresolve
        post :create_issue
        post :close_issue
        delete :unlink_issue
      end
    end
    resources :watchers, only: [:destroy, :update]
    member do
      post :regenerate_api_key
    end
    collection do
      get :search
    end
  end

  namespace :api do
    namespace :v1 do
      resources :problems, only: [:index, :show], defaults: { format: 'json' }
      resources :notices,  only: [:index], defaults: { format: 'json' }
      resources :stats, only: [], defaults: { format: 'json' } do
        collection do
          get :app
        end
      end
    end
  end

  match '/api/v3/projects/:project_id/create-notice' => 'api/v3/notices#create', via: [:post]
  match '/api/v3/projects/:project_id/notices' => 'api/v3/notices#create', via: [:post, :options]

  root to: 'apps#index'
end

app/models/problem.rb
# Represents a single Problem. The problem may have been
# reported as various Errs, but the user has grouped the
# Errs together as belonging to the same problem.

class Problem
  include Mongoid::Document
  include Mongoid::Timestamps

  CACHED_NOTICE_ATTRIBUTES = {
    messages:    :message,
    hosts:       :host,
    user_agents: :user_agent_string
  }.freeze

  field :last_notice_at, type: ActiveSupport::TimeWithZone, default: proc { Time.zone.now }
  field :first_notice_at, type: ActiveSupport::TimeWithZone, default: proc { Time.zone.now }
  field :resolved, type: Boolean, default: false
  field :resolved_at, type: Time
  field :issue_link, type: String
  field :issue_type, type: String

  # Cached fields
  field :app_name, type: String
  field :notices_count, type: Integer, default: 0
  field :message
  field :environment
  field :error_class
  field :where
  field :user_agents, type: Hash, default: {}
  field :messages,    type: Hash, default: {}
  field :hosts,       type: Hash, default: {}
  field :comments_count, type: Integer, default: 0

  index app_id: 1
  index app_name: 1
  index message: 1
  index last_notice_at: 1
  index first_notice_at: 1
  index resolved_at: 1
  index notices_count: 1

  index({
    error_class: "text",
    where:       "text",
    message:     "text",
    app_name:    "text",
    environment: "text"
  }, default_language: "english")

  belongs_to :app
  has_many :errs, inverse_of: :problem, dependent: :destroy
  has_many :comments, inverse_of: :err, dependent: :destroy

  validates :environment, presence: true
  validates :last_notice_at, :first_notice_at, presence: true

  before_create :cache_app_attributes

  scope :resolved, -> { where(resolved: true) }
  scope :unresolved, -> { where(resolved: false) }
  scope :ordered, -> { order_by(:last_notice_at.desc) }
  scope :for_apps, ->(apps) { where(:app_id.in => apps.all.map(&:id)) }
  scope :search, ->(value) { where('$text' => { '$search' => value }) }

  def self.all_else_unresolved(fetch_all)
    if fetch_all
      all
    else
      where(resolved: false)
    end
  end

  def self.in_env(env)
    env.present? ? where(environment: env) : scoped
  end

  def self.cache_notice(id, notice)
    # increment notice count
    message_digest = Digest::MD5.hexdigest(notice.message)
    host_digest = Digest::MD5.hexdigest(notice.host)
    user_agent_digest = Digest::MD5.hexdigest(notice.user_agent_string)

    Problem.where('_id' => id).find_one_and_update({
      '$set' => {
        'environment'                            => notice.environment_name,
        'error_class'                            => notice.error_class,
        'last_notice_at'                         => notice.created_at.utc,
        'message'                                => notice.message,
        'resolved'                               => false,
        'resolved_at'                            => nil,
        'where'                                  => notice.where,
        "messages.#{message_digest}.value"       => notice.message,
        "hosts.#{host_digest}.value"             => notice.host,
        "user_agents.#{user_agent_digest}.value" => notice.user_agent_string
      },
      '$inc' => {
        'notices_count'                          => 1,
        "messages.#{message_digest}.count"       => 1,
        "hosts.#{host_digest}.count"             => 1,
        "user_agents.#{user_agent_digest}.count" => 1
      }
    }, return_document: :after)
  end

  def uncache_notice(notice)
    last_notice = notices.last

    atomically do |doc|
      doc.set(
        'environment'    => last_notice.environment_name,
        'error_class'    => last_notice.error_class,
        'last_notice_at' => last_notice.created_at,
        'message'        => last_notice.message,
        'where'          => last_notice.where,
        'notices_count'  => notices_count.to_i > 1 ? notices_count - 1 : 0
      )

      CACHED_NOTICE_ATTRIBUTES.each do |k, v|
        digest = Digest::MD5.hexdigest(notice.send(v))
        field = "#{k}.#{digest}"

        if (doc[k].try(:[], digest).try(:[], :count)).to_i > 1
          doc.inc("#{field}.count" => -1)
        else
          doc.unset(field)
        end
      end
    end
  end

  def recache
    CACHED_NOTICE_ATTRIBUTES.each do |k, v|
      # clear all cached attributes
      send("#{k}=", {})

      # find only notices related to this problem
      Notice.collection.find.aggregate([
        { "$match" => { err_id: { "$in" => err_ids } } },
        { "$group" => { _id: "$#{v}", count: { "$sum" => 1 } } }
      ]).each do |agg|
        send(k)[Digest::MD5.hexdigest(agg[:_id] || 'N/A')] = {
          'value' => agg[:_id] || 'N/A',
          'count' => agg[:count]
        }
      end
    end

    first_notice = notices.order_by([:created_at, :asc]).first
    last_notice = notices.order_by([:created_at, :desc]).first

    self.notices_count = notices.count
    self.first_notice_at = first_notice.created_at if first_notice
    self.message = first_notice.message if first_notice
    self.where = first_notice.where if first_notice
    self.last_notice_at = last_notice.created_at if last_notice

    save
  end

  def url
    Rails.application.routes.url_helpers.app_problem_url(
      app,
      self,
      protocol: Errbit::Config.protocol,
      host:     Errbit::Config.host,
      port:     Errbit::Config.port
    )
  end

  def notices
    Notice.for_errs(errs).ordered
  end

  def resolve!
    self.update_attributes!(resolved: true, resolved_at: Time.zone.now)
  end

  def unresolve!
    self.update_attributes!(resolved: false, resolved_at: nil)
  end

  def unresolved?
    !resolved?
  end

  def self.merge!(*problems)
    ProblemMerge.new(problems).merge
  end

  def merged?
    errs.length > 1
  end

  def unmerge!
    attrs = { error_class: error_class, environment: environment }
    problem_errs = errs.to_a

    # associate and return all the problems
    new_problems = [self]

    # create new problems for each err that needs one
    (problem_errs[1..-1] || []).each do |err|
      new_problems << app.problems.create(attrs)
      err.update_attribute(:problem, new_problems.last)
    end

    # recache each new problem
    new_problems.each(&:recache)

    new_problems
  end

  def self.ordered_by(sort, order)
    case sort
    when "app"            then order_by(["app_name", order])
    when "message"        then order_by(["message", order])
    when "last_notice_at" then order_by(["last_notice_at", order])
    when "count"          then order_by(["notices_count", order])
    else fail("\"#{sort}\" is not a recognized sort")
    end
  end

  def cache_app_attributes
    self.app_name = app.name if app
  end

  def issue_type
    # Return issue_type if configured, but fall back to detecting app's issue tracker
    attributes['issue_type'] ||=
    (app.issue_tracker_configured? && app.issue_tracker.type_tracker) || nil
  end

private

  def attribute_count_descrease(name, value)
    counter = send(name)
    index = attribute_index(value)
    if counter[index] && counter[index]['count'] > 1
      counter[index]['count'] -= 1
    else
      counter.delete(index)
    end
    counter
  end

  def attribute_index(value)
    Digest::MD5.hexdigest(value.to_s)
  end
end

app/controllers/api/v1/problems_controller.rb
class Api::V1::ProblemsController < ApplicationController
  respond_to :json, :xml
  FIELDS = %w(_id app_id app_name environment message where first_notice_at last_notice_at resolved resolved_at notices_count)

  def show
    result = benchmark("[api/v1/problems_controller/show] query time") do
      begin
        Problem.only(FIELDS).find(params[:id])
      rescue Mongoid::Errors::DocumentNotFound
        head :not_found
        return false
      end
    end

    respond_to do |format|
      format.any(:html, :json) { render json: result } # render JSON if no extension specified on path
      format.xml { render xml: result }
    end
  end

  def index
    query = {}

    if params.key?(:start_date) && params.key?(:end_date)
      start_date = Time.parse(params[:start_date]).utc
      end_date = Time.parse(params[:end_date]).utc
      query = { :first_notice_at => { "$lte" => end_date }, "$or" => [{ resolved_at: nil }, { resolved_at: { "$gte" => start_date } }] }
    end

    results = benchmark("[api/v1/problems_controller/index] query time") do
      Problem.where(query).with(consistency: :strong).only(FIELDS).to_a
    end

    respond_to do |format|
      format.any(:html, :json) { render json: JSON.dump(results) } # render JSON if no extension specified on path
      format.xml { render xml: results }
    end
  end
end

app/controllers/problems_controller.rb
class ProblemsController < ApplicationController
  include ProblemsSearcher

  before_action :need_selected_problem, only: [
    :resolve_several, :unresolve_several, :unmerge_several
  ]

  expose(:app_scope) do
    params[:app_id] ? App.where(_id: params[:app_id]) : App.all
  end

  expose(:app) do
    AppDecorator.new app_scope.find(params[:app_id])
  end

  expose(:problem) do
    ProblemDecorator.new app.problems.find(params[:id])
  end

  expose(:all_errs) do
    params[:all_errs]
  end

  expose(:params_environement) do
    params[:environment]
  end

  expose(:problems) do
    finder = Problem.
      for_apps(app_scope).
      in_env(params_environement).
      all_else_unresolved(all_errs).
      ordered_by(params_sort, params_order)

    finder = finder.search(params[:search]) if params[:search].present?
    finder.page(params[:page]).per(current_user.per_page)
  end

  def index; end

  def show
    @notices = problem.object.notices.reverse_ordered.
      page(params[:notice]).per(1)
    @notice  = NoticeDecorator.new @notices.first
    @comment = Comment.new
  end

  def close_issue
    issue = Issue.new(problem: problem, user: current_user)
    flash[:error] = issue.errors.full_messages.join(', ') unless issue.close

    redirect_to app_problem_path(app, problem)
  end

  def create_issue
    issue = Issue.new(problem: problem, user: current_user)
    issue.body = render_to_string(*issue.render_body_args)

    flash[:error] = issue.errors.full_messages.join(', ') unless issue.save

    redirect_to app_problem_path(app, problem)
  end

  def unlink_issue
    problem.update_attribute :issue_link, nil
    redirect_to app_problem_path(app, problem)
  end

  def resolve
    problem.resolve!
    flash[:success] = t('.the_error_has_been_resolved')
    redirect_to :back
  rescue ActionController::RedirectBackError
    redirect_to app_path(app)
  end

  def resolve_several
    selected_problems.each(&:resolve!)
    flash[:success] = "Great news everyone! #{I18n.t(:n_errs_have, count: selected_problems.count)} #{I18n.t('n_errs_have.been_resolved')}."
    redirect_to :back
  end

  def unresolve_several
    selected_problems.each(&:unresolve!)
    flash[:success] = "#{I18n.t(:n_errs_have, count: selected_problems.count)} #{I18n.t('n_errs_have.been_unresolved')}."
    redirect_to :back
  end

  ##
  # Action to merge several Problem in One problem
  #
  # @param [ Array<String> ] :problems the list of problem ids
  #
  def merge_several
    if selected_problems.length < 2
      flash[:notice] = I18n.t('controllers.problems.flash.need_two_errors_merge')
    else
      ProblemMerge.new(selected_problems).merge
      flash[:notice] = I18n.t('controllers.problems.flash.merge_several.success', nb: selected_problems.count)
    end
    redirect_to :back
  end

  def unmerge_several
    all = selected_problems.flat_map(&:unmerge!)
    flash[:success] = "#{I18n.t(:n_errs_have, count: all.length)} #{I18n.t('n_errs_have.been_unmerged')}."
    redirect_to :back
  end

  def destroy_several
    DestroyProblemsByIdJob.perform_later(selected_problems_ids)
    flash[:notice] = "#{I18n.t(:n_errs, count: selected_problems.size)} #{I18n.t('n_errs.will_be_deleted')}."
    redirect_to :back
  end

  def destroy_all
    DestroyProblemsByAppJob.perform_later(app.id)
    flash[:success] = "#{I18n.t(:n_errs, count: app.problems.count)} #{I18n.t('n_errs.will_be_deleted')}."
    redirect_to :back
  rescue ActionController::RedirectBackError
    redirect_to app_path(app)
  end

  def search
    respond_to do |format|
      format.html { render :index }
      format.js
    end
  end

  ##
  # Redirect :back if no errors selected
  #
  protected def need_selected_problem
    return if err_ids.any?

    flash[:notice] = I18n.t('controllers.problems.flash.no_select_problem')
    redirect_to :back
  end
end

app/helpers/problems_helper.rb
module ProblemsHelper
  def problem_confirm(action)
    t(format('problems.confirm.%s', action)) unless Errbit::Config.confirm_err_actions.eql? false
  end

  def gravatar_tag(email, options = {})
    return nil unless email.present?

    image_tag gravatar_url(email, options), alt: email, class: 'gravatar'
  end

  def gravatar_url(email, options = {})
    return nil unless email.present?

    default_options = {
      d: Errbit::Config.gravatar_default
    }
    options.reverse_merge! default_options
    params = options.extract!(:s, :d).delete_if { |_k, v| v.blank? }
    email_hash = Digest::MD5.hexdigest(email)
    url = request.ssl? ? "https://secure.gravatar.com" : "http://www.gravatar.com"
    "#{url}/avatar/#{email_hash}?#{params.to_query}"
  end
end

app/views/problems/_issue_tracker_links.html.haml
- if app.issue_tracker_configured?
  - tracker = app.issue_tracker
  - tracker_type = tracker.type
  - if problem.issue_link.present?
    %span
      = link_to problem.issue_link, :class => "goto-issue issue-tracker-button" do
        %img.button-icon{"src" => tracker_type.icons[:goto]}
        go to issue
    %span
      = link_to unlink_issue_app_problem_path(app, problem), :method => :delete, :data => { :confirm => "Unlink err issues?" }, :class => "unlink-issue issue-tracker-button" do
        %img.button-icon{"src" => tracker_type.icons[:create]}
        unlink issue
    - if tracker.tracker.respond_to? :close_issue
      %span
        = link_to close_issue_app_problem_path(app, problem), method: :post, :class => "close-issue" do
          %img.button-icon{"src" => tracker_type.icons[:create]}
          close issue
  - elsif problem.issue_link == "pending"
    %span.disabled
      = link_to '#', :class => "create-issue issue-tracker-button" do
        %img.button-icon{"src" => tracker_type.icons[:inactive]}
        creating...
    = link_to 'retry', create_issue_app_problem_path(app, problem), :method => :post
  - else
    %span
      = link_to create_issue_app_problem_path(app, problem), method: :post, :class => "create-issue issue-tracker-button" do
        %img.button-icon{"src" => tracker_type.icons[:create]}
        create issue

app/views/problems/_search.html.haml
= form_tag search_problems_path(:all_errs => all_errs, :app_id => app_id, :sort => params_sort, :order => params_order), :method => :get, :remote => true do
    = text_field_tag :search, params[:search], :placeholder => t('.search_placeholder')

app/views/problems/_table.html.haml
- any_issue_links = problems.any?{|e| e.issue_link.present? && e.issue_link != 'pending' }
=form_tag do
  %table.errs.selectable
    %thead
      %tr
        %th= check_box_tag "toggle_problems_checkboxes"
        %th= link_for_sort t('.app')
        %th= link_for_sort t('.what_&_where').html_safe, "message"
        %th= link_for_sort t('.latest'), "last_notice_at"
        %th= link_for_sort t('.count')
        - if any_issue_links
          %th Issue
        %th= t('.resolve')
    %tbody
      - problems.each do |problem|
        %tr{:class => problem.resolved? ? 'resolved' : 'unresolved'}
          %td.select.narrow-as-possible
            %div.td-container
              = check_box_tag "problems[]", problem.id, selected_problems.member?(problem.id.to_s)
          %td.app
            %div.td-container
              = link_to problem.app.name, app_path(problem.app), class: 'name nowrap', title: problem.app.name
              - if current_page?(:controller => 'problems')
                %span.environment{class: 'nowrap', title: problem.environment}
                  = link_to problem.environment, problems_path(:environment => problem.environment)
              - else
                %span.environment{class: 'nowrap', title: problem.environment}
                  = link_to problem.environment, app_path(problem.app, :environment => problem.environment)
          %td.message
            %div.td-container
              = link_to problem.message, app_problem_path(problem.app, problem), class: 'nowrap', title: problem.message
              %em{class: 'nowrap', title: problem.where}= problem.where
              - if problem.comments_count > 0
                - comment = problem.comments.last
                %br
                .inline_comment{class: 'nowrap'}
                  - if comment.user
                    %em.commenter= (Errbit::Config.user_has_username ? comment.user.username : comment.user.email).to_s << ":"
                  %em= truncate(comment.body, :length => 100, :separator => ' ')
          %td.latest
            - value = "#{time_ago_in_words(problem.last_notice_at)} #{I18n.t('problems.table.ago')}"
            %div.td-container{class: 'nowrap', title: value}= value
          %td.count.narrow-as-possible
            %div.td-container= link_to problem.notices_count, app_problem_path(problem.app, problem)
            - if any_issue_links
              %td.issue_link.narrow-as-possible
                - if problem.app.issue_tracker_configured? && problem.issue_link.present? && problem.issue_link != 'pending'
                  = link_to image_tag("#{problem.issue_type}_goto.png"), problem.issue_link, :target => "_blank"
          %td.resolve.narrow-as-possible
            %div.td-container= link_to image_tag("thumbs-up.png"), resolve_app_problem_path(problem.app, problem),
              :title => "Resolve", :method => :put, :data => { :confirm => problem_confirm('resolve_one') },
              :class => 'resolve' if problem.unresolved?
      - if problems.none?
        %tr
          %td{:colspan => 100}
            %em No errs here
  = paginate problems
  .tab-bar
    %ul
      - %w(merge unmerge resolve unresolve delete).each do |action|
        %li= submit_tag t(".#{action}").capitalize, :id => "#{action}_problems", :class => 'button',
          :data => { :action => polymorphic_path([action == 'delete' ? 'destroy' : action, 'several_problems']),
          :confirm => problem_confirm(action) }

app/views/problems/_tally_table.html.haml
.head_and_tail
  %table.tally.head
    %tbody
      - head(rows).each do |row|
        %tr
          %td.percent= number_to_percentage(row[0], :precision => 1)
          %th.value= row[1]
    - if rows.size > head_size
      %tfoot
        %tr
          %td{:colspan => 2}
            = link_to 'Show more...', '#', :class => :show_tail
  %table.tally.tail{:style => "display: none"}
    %tbody
      - tail(rows).each do |row|
        %tr
          %td.percent= number_to_percentage(row[0], :precision => 1)
          %th.value= row[1]

app/views/problems/index.html.haml
- content_for :title, all_errs ? t('.all_errors') : t('.unresolved_errors')
- content_for :head do
  = auto_discovery_link_tag :atom, problems_path(User.token_authentication_key => current_user.authentication_token, :format => "atom"), :title => "Errbit notices at #{request.host}"

- content_for :action_bar do
  - if all_errs
    = link_to t('.hide_resolved'), problems_path(sort: params_sort, order: params_order), :class => 'button'
  - else
    = link_to t('.show_resolved'), problems_path(all_errs: true, sort: params_sort, order: params_order), :class => 'button'

%section
  = render 'problems/search', :all_errs => all_errs, :app_id => nil
%br
%section
  #problem_table.problem_table
    = render 'problems/table'

app/views/problems/search.js.haml
$("#problem_table").empty().append("#{escape_javascript(render('problems/table', :problems => problems))}");
$("#flash-messages").empty()
toggleProblemsCheckboxes()

app/views/problems/show.html.haml
- content_for :page_title, problem.message
- content_for :title_css_class, "err_show #{'resolved' if problem.resolved?}"
- content_for :title, problem.error_class || truncate(problem.message, :length => 32)
- content_for :meta do
  %strong= t('.app') + ':'
  = link_to app.name, app
  %strong= t('.where') + ':'
  = problem.where
  %br
  %strong= t('.environment') + ':'
  = problem.environment
  %strong= t('.last_notice') + ':'
  = problem.last_notice_at.to_s(:precise)
- content_for :action_bar do
  - if problem.unresolved?
    %span= link_to t('.resolve'), [:resolve, app, problem], :method => :put,
      :data => { :confirm => problem_confirm('resolve_one') }, :class => 'resolve'
  - if current_user.authentication_token
    %span
      = link_to polymorphic_path([app, problem], :format => "ics", :auth_token => current_user.authentication_token) do
        %i.fa.fa-calendar
        iCal
  %span>= link_to t('.up'), (request.env['HTTP_REFERER'] ? :back : app_problems_path(app)), :class => 'up'
  %br
  = render "issue_tracker_links"

- content_for :comments do
  %h3= t('.comments')
  - problem.comments.each do |comment|
    .window
      %table.comment
        %tr
          %th
            - if comment.user
              - if Errbit::Config.use_gravatar
                = gravatar_tag comment.user.email, :s => 24
              %span.comment-info
                = time_ago_in_words(comment.created_at, include_seconds: true) << " " + t('.ago_by')
                = link_to comment.user.email, comment.user
            - else
              %span.comment-info
                = time_ago_in_words(comment.created_at, include_seconds: true) << " " + t('.ago_by_unknown_user')
            %span.delete= link_to '&#10008;'.html_safe, [app, problem, comment], :method => :delete,
              :data => { :confirm => t("comments.confirm_delete") }, :class => "destroy-comment"
        %tr
          %td= simple_format comment.body
  = form_for [app, problem, @comment] do |comment_form|
    %p= t('.add_a_comment')
    = comment_form.text_area :body
    = comment_form.submit t('.save_comment')

%h4= @notice.try(:message)

= paginate @notices, :param_name => :notice, :theme => :notices

.tab-bar
  %ul
    %li= link_to t('.summary'), '#summary', :rel => 'summary', :class => 'button'
    %li= link_to t('.backtrace'), '#backtrace', :rel => 'backtrace', :class => 'button'
    - if @notice && @notice.user_attributes.present?
      %li= link_to t('.user'), '#user_attributes', :rel => 'user_attributes', :class => 'button'
    %li= link_to t('.environment'), '#environment', :rel => 'environment', :class => 'button'
    %li= link_to t('.parameters'), '#params', :rel => 'params', :class => 'button'
    %li= link_to t('.session'), '#session', :rel => 'session', :class => 'button'

- if @notice
  #summary
    %h3= t('.summary')
    = render 'notices/summary', :notice => @notice

  #backtrace
    %h3 Backtrace
    = render 'notices/backtrace', :backtrace => @notice.backtrace

  - if @notice.user_attributes.present?
    #user_attributes
      %h3 User
      = render 'notices/user_attributes', :user => @notice.user_attributes

  #environment
    %h3 Environment
    = render 'notices/environment', :notice => @notice

  #params
    %h3 Parameters
    = render 'notices/params', :notice => @notice

  #session
    %h3 Session
    = render 'notices/session', :notice => @notice

app/views/problems/show.ics.haml
= generate_problem_ical(problem.notices.object.order_by(:created_at.asc))